---
# Ansible Collection Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Required for Twingate operations
  - name: community.general
    version: ">=8.0.0"

  # Required for AAP operations
  # Using awx.awx (works with both AWX and Red Hat AAP)
  # Note: For Red Hat AAP, ansible.controller is preferred but requires
  # Red Hat Automation Hub access. awx.awx works fine and is publicly available.
  - name: awx.awx
    version: ">=24.0.0"

  # Optional - for VMware operations if needed
  - name: community.vmware
    version: ">=3.0.0"
